SELECT 
CATEGORIAS.ID AS ID_CATEGORIA,
CATEGORIAS.NOME AS NOME_CATEGORIA,
PRODUTOS.ID AS ID_PRODUTOS,
PRODUTOS.NOME AS NOME_PRODUTO,
PRODUTOS.PRECO AS PRECO_PRODUTO
FROM 
CATEGORIAS 
INNER JOIN 
PRODUTOS ON CATEGORIAS.ID = PRODUTOS.CATEGORIA_ID;

SELECT CATEGORIA.NOME AS NOME, 
SUM(ITEM_PEDIDO.PRECO_UNITARIO * ITEM_PEDIDO.QUANTIDADE) AS TOTAL
FROM CATEGORIA
INNER JOIN produto ON CATEGORIA.id = produto.CATEGORIA_id
INNER JOIN ITEM_PEDIDO ON produto.id = ITEM_PEDIDO.produto_id
GROUP BY CATEGORIA.id, CATEGORIA.NOME;

SELECT 
COUNT(distinct PEDIDO.id) AS PEDIDOS_REALIZADOS,
SUM(ITEM_PEDIDO.QUANTIDADE) AS PRODUTOS_VENDIDOS,
MIN(ITEM_PEDIDO.PRECO_UNITARIO * ITEM_PEDIDO.QUANTIDADE) AS PEDIDO_MAIS_BARATO,
MAX(ITEM_PEDIDO.PRECO_UNITARIO * ITEM_PEDIDO.QUANTIDADE) AS PEDIDO_MAIS_CARO,
SUM(ITEM_PEDIDO.PRECO_UNITARIO * ITEM_PEDIDO.QUANTIDADE) AS MONTANTE_VENDIDO
FROM
PEDIDO
INNER JOIN ITEM_PEDIDO ON PEDIDO.id = ITEM_PEDIDO.PEDIDO_id;

SELECT
  CLEINTE.NOME AS NOME,
  COUNT(PEDIDO.id) AS QUANTIDADE
FROM
  CLEINTE
LEFT JOIN PEDIDO ON CLEINTE.id = PEDIDO.CLEINTE_id
GROUP BY CLEINTE.id, CLEINTE.NOME
ORDER BY QUANTIDADE DESC;